server:
  port: ${PORT:8080}

spring:
  application:
    name: ecom-api-gateway
  main:
    web-application-type: reactive
  profiles:
    active: ${PROFILE:test}
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        - id: user-management-service
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/users/**

oauth2:
  token-issuer: ${TOKEN_ISSUER}


eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY_URL}

logging:
  file:
    path: /var/log/ecom-api-gateway




